---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ IPAddress }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows Service"
      win_service: 
        name: "{{ service_name }}"      
      register: service_state
      failed_when: service_state is not defined
      changed_when: false
      when: os_type == "Windows"
      ignore_errors: true

    - name: Send message to slack
      slack:
        token: 'TJ6A2L403/B01FR8JCNV9/0RpPLACul2WCa5BuD8lBlA7N'
        blocks:
          - type: section
            text:
              type: plain_text
              text: Launched {{ tower_job_id }} on {{ IPAddress }} and Service is {{ service_name }}
              emoji: true
          - type: actions
            elements:
            - type: button
              text:
                type: plain_text
                emoji: true
                text: Approve
              style: primary
              value: click_me_123
            - type: button
              text:
                type: plain_text
                emoji: true
                text: Deny
              style: danger
              value: click_me_123
            - type: button
              text:
                type: plain_text
                text: Ansible Tower
                emoji: true
              value: click_me_123
              url: https://8.9.9.22/#/home
              action_id: button-action
        channel: "ansibleadhoc"
        domain: "app.slack.com"
      register: post_out
      delegate_to: localhost
      ignore_errors: true
