---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ IPAddress }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows Service"
      win_service: 
        name: "{{ service_name }}"      
      register: service_state
      failed_when: service_state is not defined
      changed_when: false
      when: os_type == "Windows"
      ignore_errors: true

    - name: Set facts for Slack Message
      set_fact:
        payload: >-
          '{"blocks": [{"type": "section","text": {"type": "plain_text",
          "text": "Launched {{ tower_job_id }} And {{ winl1_info.stdout_lines[0] }} is {{ service_state.state }} on {{ IPAddress }}",
          "emoji": true}},{"type": "actions","elements": [{"type": "button",
          "text": {"type": "plain_text","emoji": true,
          "text": "Restart Service Job"},"style": "primary","value": "click_me_123",
          "url": "https://8.9.9.22/#/templates/job_template/17"},
          {"type": "button","text": {"type": "plain_text","emoji": true,
          "text": "Check Serivce Job"},"style": "danger","value": "click_me_123",
          "url": "https://8.9.9.22/#/templates/job_template/15"},
          {"type": "button","text": {"type": "plain_text",
          "text": "Ansible Job Log","emoji": true},"value": "click_me_123",
          "url": "https://8.9.9.22/#/jobs/playbook/{{ tower_job_id }}",
          "action_id": "button-action"}]}]}'
        surl: "https://hooks.slack.com/services/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"
      changed_when: false
      delegate_to: localhost
      ignore_errors: true

    - name: Post Message to Slack
      slack:
        token: 'TJ6A2L403/B01JLRU0DQT/H4QzGmGAgslp5NClg4DPImRZ'
        attachments:
          - blocks:
            - type: section
              text:
                type: mrkdwn
                text: Launched {{ tower_job_id }} And {{ winl1_info.stdout_lines[0] }} is {{ service_state.state }} on {{ IPAddress }}
            - type: section
              text:
                type: mrkdwn
                text: Ansible Job Log
              accessory:
                type: button
                text:
                  type: plain_text
                  text: Ansible Job Log
                url: https://8.9.9.22/#/jobs/playbook/67
        channel: "ansibleadhoc"
        domain: "app.slack.com"
#      shell: >-
#        curl -X POST -H 'Content-type: application/json' {{ surl }} -d {{ payload }}
#      args:
#        warn: no
#      uri:
#        url: "{{ surl }}"
#        method: POST
#        body: "{{ payload }}"
#        body_format: json
#        headers:
#          Content-Type: application/json
#        validate_certs: no
      changed_when: false
      delegate_to: localhost
      ignore_errors: true
