---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ IPAddress }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows Service"
      win_service: 
        name: "{{ service_name }}"      
      register: service_state
      failed_when: service_state is not defined
      changed_when: false
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows file copy"
      win_copy: 
        src: \\8.9.9.16\utils\wmi_exporter-0.4.3-amd64.msi
        dest: c:\temp\wmi_exporter-0.4.3-amd64.msi
      register: cp
      when: os_type == "Windows"
      ignore_errors: true

    - name: mount Q
      win_shell: 'New-PSDrive -Name "Q" -PSProvider "FileSystem" -Root "\\8.9.9.16\utils"'
      ignore_errors: true

    - name: copy file
      raw: 'xcopy Q:\wmi_exporter-0.4.3-amd64.msi C:\temp /Y'
      ignore_errors: true
