---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ IPAddress }}"
  gather_facts: true
  gather_subset: "all"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    hostname: "{{ ansible_facts['hostname'] }}"
    os_name: "{{ ansible_facts['os_name'] }}"
    lastboot: "{{ ansible_facts['lastboot'] }}"
    uptime: "{{ ((ansible_facts['uptime_seconds'] | int)/60)/60 }}"
    command: "{{ Command }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows Service"
      win_service: 
        name: "{{ service_name }}"      
      register: service_state
      failed_when: service_state is not defined
      changed_when: false
      when: os_type == "Windows"
      ignore_errors: true

    - name: Get Power Plan
      win_power_plan:
        name: nothing
      changed_when: false
      register: powerplan
      ignore_errors: true

    - name: Check Local Administrator
      win_user:
        name: administrator
        state: query
      changed_when: false
      register: localadmin
      ignore_errors: true

    - name: Check Windows Updates Available
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
        state: searched
      changed_when: false
      register: updates
      ignore_errors: true

    - name: Check Local Administrator via win_shell
      win_shell: $apls=get-localuser administrator; $apls.PasswordLastSet;
      changed_when: false
      register: lcladm
      when: os_type == "Windows"
      ignore_errors: true

    - name: Check Updates Installed
      win_shell: get-wmiobject -class win32_quickfixengineering | convertto-csv;
      changed_when: false
      register: upins
      when: os_type == "Windows"
      ignore_errors: true

    - debug: 
        msg: "Hostname: {{ hostname }}"
      ignore_errors: true

    - debug: 
        msg: "OS: {{ os_name }}"
      ignore_errors: true

    - debug: 
        msg: "LastBootUpTime: {{ lastboot }} , UpTime: {{ uptime }} hrs or {{ (uptime | int)/24 }} days "
      ignore_errors: true

    - debug: 
        msg: "PowerPlan: {{ powerplan.all_available_plans }}"
      ignore_errors: true

    - debug: 
        msg: "LocalAdminPwdLastSet: {{ lcladm.stdout }}"
      ignore_errors: true