---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
# - hosts: "{{ IPAddress }}"
- hosts: localhost
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: Set Facts
      set_fact:
        vch: "{{ lookup('env','VMWARE_HOST') }}"
        vusr: "{{ lookup('env','VMWARE_USER') }}"
        vpwd: "{{ lookup('env','VMWARE_PASSWORD') }}"
      no_log: true
      ignore_errors: true

    - name: Gather vmware hosts facts from vCenter
      vmware_host_facts:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
      register: all_host_facts
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - name: Gather vmware host facts from vCenter
      vmware_host_facts:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
        esxi_hostname: "{{ esxi_hostname }}"
      register: host_facts
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - name: Gather info from a esxi host using the vSphere API output schema
      vmware_host_facts:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
        esxi_hostname: "{{ esxi_hostname }}"
        schema: vsphere
        properties:
          - hardware.memorySize
          - hardware.cpuInfo.numCpuCores
          - config.product.apiVersion
          - overallStatus
          - runtime.connectionState
          - runtime.powerState 
      register: host_info
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - debug: var=all_host_facts
    - debug: var=host_facts
    - debug: var=host_info