---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
# - hosts: "{{ IPAddress }}"
- hosts: localhost
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: Set Facts
      set_fact:
        vch: "{{ lookup('env','VMWARE_HOST') }}"
        vusr: "{{ lookup('env','VMWARE_USER') }}"
        vpwd: "{{ lookup('env','VMWARE_PASSWORD') }}"
      no_log: true
      ignore_errors: true

    - name: Gather vCenter info
      vmware_about_info:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
      register: vcenter_facts
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - name: Gather vmware host facts from vCenter
      vmware_host_facts:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
        esxi_hostname: "{{ esxi_hostname }}"
      register: host_facts
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - name: Gather cluster info from given datacenter
      vmware_cluster_info:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
        datacenter: "{{ DataCenter }}"
        validate_certs: no
      register: cluster_info
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - name: Gather info from datacenter about specific cluster
      vmware_cluster_info:
        hostname: "{{ vch }}"
        username: "{{ vusr }}"
        password: "{{ vpwd }}"
        cluster_name: "{{ Cluster }}"
      register: cluster_facts
      delegate_to: localhost
      changed_when: false
      ignore_errors: true

    - debug: var=vcenter_facts
    - debug: var=host_facts
    - debug: var=cluster_info
    - debug: var=cluster_facts
