---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ IPAddress }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ Command }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Windows Service"
      win_service: 
        name: "{{ service_name }}"      
      register: service_state
      failed_when: service_state is not defined
      changed_when: false
      when: os_type == "Windows"
      ignore_errors: true

    - name: set fact
      set_fact:
        bvalue: '{\"extra_vars\": { \"Command\": \"{{ winl1_info.stdout_lines[0] }}\"}}'
      ignore_errors: true

    - name: Post Message to Slack
      slack:
        token: 'TJ6A2L403/B01J63MV10X/w4AYbJ0mtY2vOWBHEQ6gZpI4'
        attachments:
          - title: Launched {{ tower_job_id }} and {{ winl1_info.stdout_lines[0] }} is {{ service_state.state }} on {{ IPAddress }}
            text: "*Actions:*"
            actions:
            - type: button
              text: Restart {{ winl1_info.stdout_lines[0] }} on {{ IPAddress }}
              style: primary
              url: https://8.9.9.22/#/templates/job_template/17
            - type: button
              text: Skip {{ winl1_info.stdout_lines[0] }} status on {{ IPAddress }}
              style: danger
              url: https://8.9.9.22/#/templates/job_template/15
            - type: button
              text: Check Job Log
              url: https://8.9.9.22/#/jobs/playbook/{{ tower_job_id }}
        channel: "ansibleadhoc"
        domain: "app.slack.com"
      changed_when: false
      delegate_to: localhost
      ignore_errors: true

    - name: Post Message to Slack with Buttons
      slack:
        token: 'TJ6A2L403/B01JM3UNYPL/0wI4NDJyCu6Bq5rfdTNa0M76'
        attachments:
          - title: Launched {{ tower_job_id }} and {{ winl1_info.stdout_lines[0] }} is {{ service_state.state }} on {{ IPAddress }}
            text: "*Actions:*"
            actions:
            - type: button
              text: Restart {{ winl1_info.stdout_lines[0] }} on {{ IPAddress }}
              style: primary
              url: https://8.9.9.22/#/templates/job_template/17
            - type: button
              text: Check {{ winl1_info.stdout_lines[0] }} status on {{ IPAddress }}
              style: danger
#              url: https://8.9.9.22/#/templates/job_template/15
              value: "'{{ bvalue }}'"
            - type: button
              text: Check Job Log
              url: https://8.9.9.22/#/jobs/playbook/{{ tower_job_id }}
        channel: "automation"
        domain: "app.slack.com"
      changed_when: false
      delegate_to: localhost
      ignore_errors: true