---
# This is a Master Playbook that parses alert information
# Author: B M Krishna Reddy Kolli
- hosts: localhost
  vars:
    slack_token: "TJ6A2L403/B01FR8JCNV9/0RpPLACul2WCa5BuD8lBlA7N"
    to: "ansibleadhoc"
    host_ip: "{{ hostvars['localhost']['host_ip'] }}"
    role_name: "{{ hostvars['localhost']['role_name'] }}"
    mesge: >-
      "{% if (hostvars[host_ip]['host_reachable']|bool) == true %} 
      {{ host_ip }} is connecting
      {% else %} {{ host_ip }} is unreachable{% endif %}"
  tasks:
    - name: Send message to slack
      slack:
        token: 'TJ6A2L403/B01FR8JCNV9/0RpPLACul2WCa5BuD8lBlA7N'
        attachments:
          - text: "{{ command }} {{ host_ip }} {{ mesge }}"
            title: "Devlopment Testing"
        channel: "ansibleadhoc"
        domain: "app.slack.com"
      register: post_out
      ignore_errors: true