---
# This is a Master Playbook that parses alert information
# Author: B M Krishna Reddy Kolli
- hosts: localhost
  vars:
    host_ip: "{{ hostvars['localhost']['host_ip'] }}"
    job_msg: "{{ hostvars[host_ip]['job_msg'] }}"
    mesge: >-
      "{% if (hostvars[host_ip]['host_reachable']|bool) == true %} 
      {{ host_ip }} is connecting
      {% else %} {{ host_ip }} is unreachable{% endif %}"
  tasks:
    - name: Send message to slack
      slack:
        token: 'TJ6A2L403/B01JSK4ACTW/jeA905Q6xodI7SP0o0WBC6N5'
        attachments:
          - text: "{{ job_msg }}"
            title: Launched {{ tower_job_id }} Output of "{{ command }}" on {{ host_ip }}
        channel: "ansibleadhoc"
        domain: "app.slack.com"
      register: post_out
      ignore_errors: true