---
# Level 1 Diagnosis for Windows and Linux
- hosts: "{{ hostvars['localhost']['host_ip'] }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ hostvars['localhost']['command'] }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Linux"
      shell: "{{ command }}"
      changed_when: false
      register: linuxl1_info
      when: (os_type != "Windows")
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: >-
          Output of "{{ command }}" on {{ hostvars['localhost']['host_info'] }}:{{ os_type }} 
          {{ winl1_info.stdout }}
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: >-
          Output of "{{ command }}" on {{ hostvars['localhost']['host_info'] }}:{{ os_type }} 
          {{ linuxl1_info.stdout }}
      when: (os_type != "Windows")
      ignore_errors: true
