---
# This is a Master Playbook that executes command on node
# Author: B M Krishna Reddy Kolli
- hosts: "{{ hostvars['localhost']['host_ip'] }}"
  vars:
    os_type: "{{ ansible_facts['os_family'] }}"
    command: "{{ hostvars['localhost']['command'] }}"
  tasks:
    - name: "Windows"
      win_shell: "{{ command }}"
      changed_when: false
      register: winl1_info
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Linux"
      shell: "{{ command }}"
      changed_when: false
      register: linuxl1_info
      when: (os_type != "Windows")
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: "Platform:{{ os_type }}; Output:{{ winl1_info.stdout }}"
      when: os_type == "Windows"
      ignore_errors: true

    - name: "Set job_msg"
      set_fact:
        job_msg: "Platform:{{ os_type }}; Output:{{ linuxl1_info.stdout }}"
      when: (os_type != "Windows")
      ignore_errors: true